/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.experiencia.programa;

import com.experiencia.entidades.Puntos;
import com.experiencia.entidades.PuntuacionGeneral;
import com.experiencia.entidades.Usabilidad;
import java.awt.Color;

/**
 *
 * @author Facundo
 */
public class QuintaPestania extends javax.swing.JFrame {

    private PuntuacionGeneral puntuacionGeneral;
    private int puntosCapEntendido;
    private int puntosCapOperado;
    private int puntosCapAtractivo;
    /**
     * Creates new form QuintaPestania
     */
    public QuintaPestania() {
        initComponents();
        this.getContentPane().setBackground(new Color(84, 86, 86));
        this.setLocationRelativeTo(null);
        jRadioAyudaTrue.setSelected(true);
        jRadioManualTrue.setSelected(true);
    }

    public void setPuntuacionGeneral(PuntuacionGeneral puntuacionGeneral) {
        this.puntuacionGeneral = puntuacionGeneral;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioAyudaTrue = new javax.swing.JRadioButton();
        jRadioAyudaFalse = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jRadioManualTrue = new javax.swing.JRadioButton();
        jRadioManualFalse = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxAsistencia = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxCantPasos = new javax.swing.JComboBox<>();
        jButtonSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Algoritmo de Calidad");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usabilidad del sistema");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Capacidad de ser entendido");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("y botones de acción?");
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("¿Posee ayuda contextual sobre menús");
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jRadioAyudaTrue.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRadioAyudaTrue.setForeground(new java.awt.Color(255, 255, 255));
        jRadioAyudaTrue.setText("Si");
        jRadioAyudaTrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioAyudaTrueActionPerformed(evt);
            }
        });

        jRadioAyudaFalse.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRadioAyudaFalse.setForeground(new java.awt.Color(255, 255, 255));
        jRadioAyudaFalse.setText("No");
        jRadioAyudaFalse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioAyudaFalseActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("¿Posee un manual de usuario?");
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jRadioManualTrue.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRadioManualTrue.setForeground(new java.awt.Color(255, 255, 255));
        jRadioManualTrue.setText("Si");
        jRadioManualTrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioManualTrueActionPerformed(evt);
            }
        });

        jRadioManualFalse.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRadioManualFalse.setForeground(new java.awt.Color(255, 255, 255));
        jRadioManualFalse.setText("No");
        jRadioManualFalse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioManualFalseActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Capacidad de ser operado");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("El sistema puede ser utilizado sin");
        jLabel9.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("asistencia adicional");
        jLabel10.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jComboBoxAsistencia.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBoxAsistencia.setMaximumRowCount(3);
        jComboBoxAsistencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "Medianamente", "No", "" }));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Capacidad de ser atractivo para el usuario");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Permite realizar las operaciones en: ");
        jLabel12.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jComboBoxCantPasos.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBoxCantPasos.setMaximumRowCount(3);
        jComboBoxCantPasos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 o 2 pasos", "Entre 3 y 5 pasos", "6 o más pasos", " ", " " }));

        jButtonSiguiente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(114, 114, 114))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jRadioAyudaTrue, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioAyudaFalse, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(26, 26, 26)
                                .addComponent(jRadioManualTrue, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioManualFalse, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxCantPasos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 29, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jButtonSiguiente)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioAyudaTrue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioAyudaFalse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioManualFalse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioManualTrue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addComponent(jComboBoxAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCantPasos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButtonSiguiente)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        if(jRadioAyudaFalse.isSelected() && jRadioManualFalse.isSelected()){
            puntosCapEntendido += Puntos.MALA.getPuntos();
        } else if(jRadioAyudaTrue.isSelected() && jRadioManualTrue.isSelected()) {
            puntosCapEntendido += Puntos.BUENA.getPuntos();
        } else {
            puntosCapEntendido += Puntos.REGULAR.getPuntos();
        }
        String capOperado = (String) jComboBoxAsistencia.getSelectedItem();
        switch(capOperado) {
            case "Si": puntosCapOperado += Puntos.BUENA.getPuntos();break;
            case "Medianamente": puntosCapOperado += Puntos.REGULAR.getPuntos();break;
            case "No": puntosCapOperado += Puntos.MALA.getPuntos();break;
        }
        String pasos = (String) jComboBoxCantPasos.getSelectedItem();
        switch(pasos){
            case "1 o 2 pasos": puntosCapAtractivo += Puntos.BUENA.getPuntos();break;
            case "Entre 3 y 5 pasos": puntosCapAtractivo += Puntos.REGULAR.getPuntos();break;
            case "6 o más pasos": puntosCapAtractivo += Puntos.MALA.getPuntos();break;
        }
        asignarPuntos();
        SextaPestania portabilidad = new SextaPestania();
        portabilidad.requestFocusInWindow();
        portabilidad.setPuntuacionGeneral(puntuacionGeneral);
        portabilidad.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jRadioAyudaFalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioAyudaFalseActionPerformed
        jRadioAyudaTrue.setSelected(false);
    }//GEN-LAST:event_jRadioAyudaFalseActionPerformed

    private void jRadioAyudaTrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioAyudaTrueActionPerformed
        jRadioAyudaFalse.setSelected(false);
    }//GEN-LAST:event_jRadioAyudaTrueActionPerformed

    private void jRadioManualFalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioManualFalseActionPerformed
        jRadioManualTrue.setSelected(false);
    }//GEN-LAST:event_jRadioManualFalseActionPerformed

    private void jRadioManualTrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioManualTrueActionPerformed
        jRadioManualFalse.setSelected(false);
    }//GEN-LAST:event_jRadioManualTrueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuintaPestania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new QuintaPestania().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JComboBox<String> jComboBoxAsistencia;
    private javax.swing.JComboBox<String> jComboBoxCantPasos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioAyudaFalse;
    private javax.swing.JRadioButton jRadioAyudaTrue;
    private javax.swing.JRadioButton jRadioManualFalse;
    private javax.swing.JRadioButton jRadioManualTrue;
    // End of variables declaration//GEN-END:variables

    private void asignarPuntos() {
        puntuacionGeneral.getUsabilidad().replace(Usabilidad.CAPENTENDIDO.getAtributo(), puntosCapEntendido);
        puntuacionGeneral.getUsabilidad().replace(Usabilidad.CAPOPERADO.getAtributo(), puntosCapOperado);
        puntuacionGeneral.getUsabilidad().replace(Usabilidad.CAPATRACTIVO.getAtributo(), puntosCapAtractivo);
        puntuacionGeneral.sumar(puntosCapEntendido);
        puntuacionGeneral.sumar(puntosCapOperado);
        puntuacionGeneral.sumar(puntosCapAtractivo);
    }
}
