/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.experiencia.programa;

import com.experiencia.entidades.Fiabilidad;
import com.experiencia.entidades.Puntos;
import com.experiencia.entidades.PuntuacionGeneral;
import java.awt.Color;

/**
 *
 * @author Facundo
 */
public class TercerPestania extends javax.swing.JFrame {

    private PuntuacionGeneral puntuacionGeneral;
    private int puntosToleranciaFallos;
    private int puntosRecuperacion;
    /**
     * Creates new form TercerPestania
     */
    public TercerPestania() {
        initComponents();
        this.getContentPane().setBackground(new Color(84, 86, 86));
        this.setLocationRelativeTo(null);
        jRadioEstadoTrue.setSelected(true);
        jRadioLogTrue.setSelected(true);
        jRadioReanudaTrue.setSelected(true);
        jRadioRecuperaTrue.setSelected(true);
    }

    public void setPuntuacionGeneral(PuntuacionGeneral puntuacionGeneral) {
        this.puntuacionGeneral = puntuacionGeneral;
        this.getContentPane().setBackground(new Color(84, 86, 86));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioRecuperaTrue = new javax.swing.JRadioButton();
        jRadioRecuperaFalse = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jRadioLogTrue = new javax.swing.JRadioButton();
        jRadioLogFalse = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jRadioReanudaTrue = new javax.swing.JRadioButton();
        jRadioReanudaFalse = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jRadioEstadoTrue = new javax.swing.JRadioButton();
        jRadioEstadoFalse = new javax.swing.JRadioButton();
        jButtonSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Algoritmo de Calidad");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fiabilidad del sistema");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tolerancia a Fallos");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cuando se produce un fallo, ¿recupera correctamente los datos?");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jRadioRecuperaTrue.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRadioRecuperaTrue.setForeground(new java.awt.Color(255, 255, 255));
        jRadioRecuperaTrue.setText("Si");
        jRadioRecuperaTrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRecuperaTrueActionPerformed(evt);
            }
        });

        jRadioRecuperaFalse.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRadioRecuperaFalse.setForeground(new java.awt.Color(255, 255, 255));
        jRadioRecuperaFalse.setText("No");
        jRadioRecuperaFalse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRecuperaFalseActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("¿Se realiza un log actividades?");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jRadioLogTrue.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRadioLogTrue.setForeground(new java.awt.Color(255, 255, 255));
        jRadioLogTrue.setText("Si");
        jRadioLogTrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioLogTrueActionPerformed(evt);
            }
        });

        jRadioLogFalse.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRadioLogFalse.setForeground(new java.awt.Color(255, 255, 255));
        jRadioLogFalse.setText("No");
        jRadioLogFalse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioLogFalseActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Capacidad de recuperación de errores");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cuando se produce un fallo, ¿el sistema reanuda sus actividades?");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel8.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jRadioReanudaTrue.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRadioReanudaTrue.setForeground(new java.awt.Color(255, 255, 255));
        jRadioReanudaTrue.setText("Si");
        jRadioReanudaTrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioReanudaTrueActionPerformed(evt);
            }
        });

        jRadioReanudaFalse.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRadioReanudaFalse.setForeground(new java.awt.Color(255, 255, 255));
        jRadioReanudaFalse.setText("No");
        jRadioReanudaFalse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioReanudaFalseActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cuando se produce un fallo, ¿el sistema recupera el estado en el que estaba?");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel9.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jRadioEstadoTrue.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRadioEstadoTrue.setForeground(new java.awt.Color(255, 255, 255));
        jRadioEstadoTrue.setText("Si");
        jRadioEstadoTrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioEstadoTrueActionPerformed(evt);
            }
        });

        jRadioEstadoFalse.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRadioEstadoFalse.setForeground(new java.awt.Color(255, 255, 255));
        jRadioEstadoFalse.setText("No");
        jRadioEstadoFalse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioEstadoFalseActionPerformed(evt);
            }
        });

        jButtonSiguiente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSiguiente)
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jRadioLogTrue, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jRadioLogFalse, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jRadioReanudaTrue, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jRadioReanudaFalse, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jRadioEstadoTrue, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jRadioEstadoFalse, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(200, 200, 200)
                    .addComponent(jRadioRecuperaTrue, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(44, 44, 44)
                    .addComponent(jRadioRecuperaFalse, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(219, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(53, 53, 53)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioLogFalse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioLogTrue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioReanudaFalse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioReanudaTrue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioEstadoFalse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioEstadoTrue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSiguiente)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(136, 136, 136)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jRadioRecuperaFalse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRadioRecuperaTrue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(301, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        if(jRadioRecuperaFalse.isSelected() && jRadioLogFalse.isSelected()){
            puntosToleranciaFallos += Puntos.MALA.getPuntos();
        } else if(jRadioRecuperaTrue.isSelected() && jRadioLogTrue.isSelected()) {
            puntosToleranciaFallos += Puntos.BUENA.getPuntos();
        } else {
            puntosToleranciaFallos += Puntos.REGULAR.getPuntos();
        }
        if(jRadioReanudaFalse.isSelected() && jRadioEstadoFalse.isSelected()){
            puntosRecuperacion += Puntos.MALA.getPuntos();
        } else if(jRadioReanudaTrue.isSelected() && jRadioEstadoTrue.isSelected()){
            puntosRecuperacion += Puntos.BUENA.getPuntos();
        } else {
            puntosRecuperacion += Puntos.REGULAR.getPuntos();
        }
        asignarPuntos();
        CuartaPestania mantenibilidad = new CuartaPestania();
        mantenibilidad.requestFocusInWindow();
        mantenibilidad.setPuntuacionGeneral(puntuacionGeneral);
        mantenibilidad.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jRadioRecuperaFalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRecuperaFalseActionPerformed
        jRadioRecuperaTrue.setSelected(false);
    }//GEN-LAST:event_jRadioRecuperaFalseActionPerformed

    private void jRadioRecuperaTrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRecuperaTrueActionPerformed
        jRadioRecuperaFalse.setSelected(false);
    }//GEN-LAST:event_jRadioRecuperaTrueActionPerformed

    private void jRadioLogFalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioLogFalseActionPerformed
        jRadioLogTrue.setSelected(false);
    }//GEN-LAST:event_jRadioLogFalseActionPerformed

    private void jRadioLogTrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioLogTrueActionPerformed
        jRadioLogFalse.setSelected(false);
    }//GEN-LAST:event_jRadioLogTrueActionPerformed

    private void jRadioReanudaFalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioReanudaFalseActionPerformed
        jRadioReanudaTrue.setSelected(false);
    }//GEN-LAST:event_jRadioReanudaFalseActionPerformed

    private void jRadioReanudaTrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioReanudaTrueActionPerformed
        jRadioRecuperaFalse.setSelected(false);
    }//GEN-LAST:event_jRadioReanudaTrueActionPerformed

    private void jRadioEstadoFalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioEstadoFalseActionPerformed
        jRadioEstadoTrue.setSelected(false);
    }//GEN-LAST:event_jRadioEstadoFalseActionPerformed

    private void jRadioEstadoTrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioEstadoTrueActionPerformed
        jRadioEstadoFalse.setSelected(false);
    }//GEN-LAST:event_jRadioEstadoTrueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TercerPestania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TercerPestania().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioEstadoFalse;
    private javax.swing.JRadioButton jRadioEstadoTrue;
    private javax.swing.JRadioButton jRadioLogFalse;
    private javax.swing.JRadioButton jRadioLogTrue;
    private javax.swing.JRadioButton jRadioReanudaFalse;
    private javax.swing.JRadioButton jRadioReanudaTrue;
    private javax.swing.JRadioButton jRadioRecuperaFalse;
    private javax.swing.JRadioButton jRadioRecuperaTrue;
    // End of variables declaration//GEN-END:variables

    private void asignarPuntos() {
        puntuacionGeneral.getFiabilidad().replace(Fiabilidad.TOLFALLOS.getAtributo(), puntosToleranciaFallos);
        puntuacionGeneral.getFiabilidad().replace(Fiabilidad.RECUPERACION.getAtributo(), puntosRecuperacion);
        puntuacionGeneral.sumar(puntosToleranciaFallos);
        puntuacionGeneral.sumar(puntosRecuperacion);
    }
}
