/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.experiencia.programa;

import com.experiencia.entidades.Mantenibilidad;
import com.experiencia.entidades.Puntos;
import com.experiencia.entidades.PuntuacionGeneral;
import java.awt.Color;

/**
 *
 * @author Facundo
 */
public class CuartaPestania extends javax.swing.JFrame {

    private PuntuacionGeneral puntuacionGeneral;
    private int puntosComentarios;
    private int puntosComplejidad;
    private int puntosFallas;
    /**
     * Creates new form CuartaPestania
     */
    public CuartaPestania() {
        initComponents();
        this.getContentPane().setBackground(new Color(84, 86, 86));
        this.setLocationRelativeTo(null);
    }

    public void setPuntuacionGeneral(PuntuacionGeneral puntuacionGeneral) {
        this.puntuacionGeneral = puntuacionGeneral;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxComentarios = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxComplejidad = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxFallas = new javax.swing.JComboBox<>();
        jButtonSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Experiencia de Usuario");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mantenibilidad del sistema");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Capacidad del codigo para ser analizado");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Densidad de comentarios en el codigo: ");
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jComboBoxComentarios.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBoxComentarios.setMaximumRowCount(3);
        jComboBoxComentarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buena", "Regular", "Mala", " " }));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Capacidad del codigo para ser cambiado");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Promedio de fallas por prueba:");
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jComboBoxComplejidad.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBoxComplejidad.setMaximumRowCount(3);
        jComboBoxComplejidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baja", "Regular", "Alta", "" }));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Estabilidad");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Complejidad del codigo:");
        jLabel9.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jComboBoxFallas.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBoxFallas.setMaximumRowCount(3);
        jComboBoxFallas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entre 0 y 1", "Entre 2 y 4", "5 o más", "" }));

        jButtonSiguiente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(87, 87, 87))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(10, 10, 10)
                                .addComponent(jComboBoxComplejidad, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxFallas, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jButtonSiguiente)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxComentarios, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxComplejidad, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxFallas)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(jButtonSiguiente)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        String densidadComentarios = (String) jComboBoxComentarios.getSelectedItem();
        switch(densidadComentarios){
            case "Buena": puntosComentarios += Puntos.BUENA.getPuntos();break;
            case "Regular": puntosComentarios += Puntos.REGULAR.getPuntos();break;
            case "Mala": puntosComentarios += Puntos.MALA.getPuntos();break;
        }
        String complejidadCodigo = (String) jComboBoxComplejidad.getSelectedItem();
        switch(complejidadCodigo){
            case "Baja": puntosComplejidad += Puntos.BUENA.getPuntos();break;
            case "Regular": puntosComplejidad += Puntos.REGULAR.getPuntos();break;
            case "Alta": puntosComplejidad += Puntos.MALA.getPuntos();break;
        }
        String fallas = (String) jComboBoxFallas.getSelectedItem();
        switch(fallas){
            case "Entre 0 y 1": puntosFallas += Puntos.BUENA.getPuntos();break;
            case "Entre 2 y 4": puntosFallas += Puntos.REGULAR.getPuntos();break;
            case "5 o más": puntosFallas += Puntos.MALA.getPuntos();break;
        }
        asignarPuntos();
        QuintaPestania usabilidad = new QuintaPestania();
        usabilidad.requestFocusInWindow();
        usabilidad.setPuntuacionGeneral(puntuacionGeneral);
        usabilidad.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuartaPestania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CuartaPestania().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JComboBox<String> jComboBoxComentarios;
    private javax.swing.JComboBox<String> jComboBoxComplejidad;
    private javax.swing.JComboBox<String> jComboBoxFallas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    private void asignarPuntos() {
        puntuacionGeneral.getMantenibilidad().replace(Mantenibilidad.ANALIZADO.getAtributo(), puntosComentarios);
        puntuacionGeneral.getMantenibilidad().replace(Mantenibilidad.CAMBIADO.getAtributo(), puntosComplejidad);
        puntuacionGeneral.getMantenibilidad().replace(Mantenibilidad.ESTABILIDAD.getAtributo(), puntosFallas);
        puntuacionGeneral.sumar(puntosComentarios);
        puntuacionGeneral.sumar(puntosComplejidad);
        puntuacionGeneral.sumar(puntosFallas);
    }
}
